services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - cp config/database.travis.yml config/database.yml
  - gem update --system
  - gem update bundler
